### ISSUE TITLE
Publish type description as JSON

### ISSUE THREAD

**Issue by nicolas377** [gpsystem/geofs-types#65]
We're currently using typedoc to generate a website version of the types, which will be very useful as documentation is added. TypeDoc also provides a way to create a JSON file that describes all the types in a more parsable format.

Here's the current todo list. Nothing has been implemented in the dev branch for this, so I'm still open to suggestions on better implementations:

- [ ] In the release workflow's npm publishing step, run `npm run docs -- --json types.json`
- [ ] #68
  - add types.json to the files array

**Comment by nicolas377** [comment]
Here's a quick rundown of my ideas.
- When the release workflow is triggered, also build the docs with the `--json` flag set to `types.json`
- Publish `types.json` along with the npm package.

In order for all of that to happen in an automated manner, here are some more things we should do, but aren't required for this.
- Use `standard-version` to automate the release process locally (generating changelogs, committing and tagging releases)
- In the release workflow, use a separate job to extract the release notes from the changelog and generate a github release. (see the release workflow from [create-geofs-plugin](https://github.com/gpsystem/create-geofs-plugin/blob/main/.github/workflows/release.yml))
- Add typedoc as a dev dependency (it wasn't added in #58)

I'm adding the steps needed to get the above done to the todo for now, but I'm open to suggestions of better implementations.

**Comment by Guy-Adler** [comment]
The file size of the generated JSON is about 3MB, which is huge compared to the types folder (~100KB). Releasing this file, which is useless for most people, in the package seems to me like a waste of space and a major inconvenience. Are we able to generate this file in the relevant workflow (create-geofs-plugin#94) instead?

**Comment by nicolas377** [comment]
I agree with that, this is pretty unnecessary. I'll go ahead and close this.
